# Imports

In [29]:
import pandas as pd
import scipy.stats
import numpy

# Load data

In [113]:
data = pd.read_csv('data/DC_Properties.csv')

C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [114]:
data

Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8   
1                1       3          1      Warm Cool  Y        2.0     11   
2                2       3          1  Hot Water Rad  Y        2.0      9   
3                3       3          1  Hot Water Rad  Y        2.0      8   
4                4       2          1      Warm Cool  Y        1.0     11   
5                5       3          2  Hot Water Rad  Y        1.0     10   
6                6       1          0      Warm Cool  Y        2.0      5   
7                7       3          1  Hot Water Rad  Y        2.0      8   
8                8       3          1      Warm Cool  Y        2.0      7   
9                9       1          1  Hot Water Rad  Y        1.0      6   
10              10       3          0     Forced Air  N        3.0     12   
11              11       5          0  Hot Water Rad  Y        3.0     16   
12              12       2          0  Hot Water Rad  N        2.0      9   
13              13       2          0      Warm Cool  Y        2.0     11   
14              14       3          1      Warm Cool  Y        2.0      5   
15              15       2          1      Warm Cool  Y        2.0      9   
16              16       3          1      Warm Cool  Y        1.0      8   
17              17       2          0  Hot Water Rad  N        1.0      6   
18              18       3          1  Hot Water Rad  Y        2.0     10   
19              19       3          1  Hot Water Rad  Y        2.0      9   
20              20       3          1  Hot Water Rad  Y        1.0     14   
21              21       3          0     Forced Air  Y        2.0     12   
22              22       1          0     Forced Air  Y        1.0      6   
23              23       2          1     Forced Air  Y        1.0      5   
24              24       2          1  Hot Water Rad  Y        1.0      8   
25              25       1          0  Hot Water Rad  N        1.0      8   
26              26       1          0  Hot Water Rad  N        1.0     10   
27              27       3          0  Hot Water Rad  Y        4.0      9   
28              28       3          0      Warm Cool  Y        2.0     10   
29              29       3          1     Forced Air  Y        2.0     11   
...            ...     ...        ...            ... ..        ...    ...   
158927      158927       2          0        Ht Pump  Y        NaN      6   
158928      158928       2          1        Ht Pump  Y        NaN      5   
158929      158929       2          1        Ht Pump  Y        NaN      5   
158930      158930       2          0     Forced Air  N        NaN      4   
158931      158931       2          1     Forced Air  N        NaN      4   
158932      158932       2          1     Forced Air  N        NaN      4   
158933      158933       2          0        Ht Pump  Y        NaN      4   
158934      158934       1          1        Ht Pump  Y        NaN      3   
158935      158935       1          0        Ht Pump  Y        NaN      3   
158936      158936       1          0        Ht Pump  Y        NaN      3   
158937      158937       1          0     Forced Air  Y        NaN      4   
158938      158938       2          0      Warm Cool  Y        NaN      7   
158939      158939       1          0     Forced Air  Y        NaN      4   
158940      158940       2          0     Forced Air  Y        NaN      7   
158941      158941       1          0     Forced Air  Y        NaN      4   
158942      158942       2          0     Forced Air  Y        NaN      7   
158943      158943       2          1     Forced Air  Y        NaN      5   
158944      158944       2          1     Forced Air  Y        NaN      5   
158945      158945       1          0     Forced Air  Y        NaN      3   
158946      158946       1          0     Forced Air  Y        NaN      4   
1589

In [5]:
data.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

# Calculate Chi²-Tests

In [21]:
c_table_SQUARE_QUADRANT = pd.crosstab(data.SQUARE, data.QUADRANT)
chi2, p, df, exp_obs = scipy.stats.chi2_contingency(c_table_SQUARE_QUADRANT)
p

0.0

In [52]:
data.LONGITUDE.corr(data.X)

0.9998966935474912

In [50]:
c_table_LONGITUDE_X = pd.crosstab(data.LONGITUDE, data.X)
chi2, p, df, exp_obs = scipy.stats.chi2_contingency(c_table_LONGTITUDE_X)
p

0.0

In [48]:
data.LATITUDE.corr(data.Y)

0.9999189587060735

In [45]:
c_table_LATITUDE_Y = pd.crosstab(data.LATITUDE, data.Y)
chi2, p, df, exp_obs = scipy.stats.chi2_contingency(c_table_LATITUDE_Y)
p, chi2

(0.0, 519807421.8700215)

In [54]:
c_table_NBHD_SUBNBHD = pd.crosstab(data.ASSESSMENT_NBHD, data.ASSESSMENT_SUBNBHD)
chi2, p, df, exp_obs = scipy.stats.chi2_contingency(c_table_NBHD_SUBNBHD)
p, chi2

(0.0, 3919100.0856282106)

In [57]:
c_table_BLOCK_TRACT = pd.crosstab(data.CENSUS_BLOCK, data.CENSUS_TRACT)
chi2, p, df, exp_obs = scipy.stats.chi2_contingency(c_table_BLOCK_TRACT)
p, chi2

(0.0, 18028670.0)

All correlation and chi² calculations show a high correlation and significance between the selected columns. (Small p value means that the null hypthesis that row and column are independent can be rejected.) They are all more or less geographical data about the specific property, so a high correlaltion can be expected. Because they have such high dependets, it is useful to drop some of the columns and only keep a few (one) that gives information about the location. Otherwise, the model would use independent variables that already have some relationship. 

In [58]:
c_table_BATHRM_BEDRM = pd.crosstab(data.BATHRM, data.BEDRM)
chi2, p, df, d = scipy.stats.chi2_contingency(c_table_BATHRM_BEDRM)

In [148]:
def chi2_test(col, row):
    table = pd.crosstab(col, row)
    chi2, p, df, exp_obs = scipy.stats.chi2_contingency(table)
    print(p)
    print(table)
    print(exp_obs)
    '''return chi2, p, exp_obs, df'''

In [149]:
chi2_test(data.HEAT, data.AC)

0.0
AC               0      N      Y
HEAT                            
Air Exchng       2     23     14
Air-Oil          0     66     51
Elec Base Brd    0    135    216
Electric Rad     0     95     49
Evp Cool         0      2     48
Forced Air       2   6882  47088
Gravity Furnac   0    108     32
Hot Water Rad   19  35367  11816
Ht Pump         10    736  20666
Ind Unit         0     36     14
No Data         32     82    216
Wall Furnace     0    270    850
Warm Cool        0    257  33371
Water Base Brd   0    213    189
[[1.59477091e-02 1.08621074e+01 2.81219449e+01]
 [4.78431274e-02 3.25863221e+01 8.43658348e+01]
 [1.43529382e-01 9.77589663e+01 2.53097504e+02]
 [5.88838491e-02 4.01062426e+01 1.03834874e+02]
 [2.04457809e-02 1.39257787e+01 3.60537755e+01]
 [2.20699938e+01 1.50320425e+04 3.89178875e+04]
 [5.72481866e-02 3.89921803e+01 1.00950572e+02]
 [1.93016350e+01 1.31464921e+04 3.40362063e+04]
 [8.75570123e+00 5.96357546e+03 1.54396688e+04]
 [2.04457809e-02 1.39257787e+01 3.60

In [127]:
print(data.AC.shape)
data.AC[data["AC"] != '0'].shape

(158957,)


(158892,)

In [137]:
chi2_test(data.HEAT, data.AC[data.AC != '0'])

0.0
AC                  N      Y
HEAT                        
Air Exchng         23     14
Air-Oil            66     51
Elec Base Brd     135    216
Electric Rad       95     49
Evp Cool            2     48
Forced Air       6882  47088
Gravity Furnac    108     32
Hot Water Rad   35367  11816
Ht Pump           736  20666
Ind Unit           36     14
No Data            82    216
Wall Furnace      270    850
Warm Cool         257  33371
Water Base Brd    213    189
[[1.03092918e+01 2.66907082e+01]
 [3.25996526e+01 8.44003474e+01]
 [9.77989578e+01 2.53201042e+02]
 [4.01226493e+01 1.03877351e+02]
 [1.39314755e+01 3.60685245e+01]
 [1.50376346e+04 3.89323654e+04]
 [3.90081313e+01 1.00991869e+02]
 [1.31465761e+04 3.40364239e+04]
 [5.96322876e+03 1.54387712e+04]
 [1.39314755e+01 3.60685245e+01]
 [8.30315938e+01 2.14968406e+02]
 [3.12065050e+02 8.07934950e+02]
 [9.36975314e+03 2.42582469e+04]
 [1.12009063e+02 2.89990937e+02]]


In [199]:
tab = pd.crosstab(data.HEAT, data.AC)

In [155]:
exp = scipy.stats.contingency.expected_freq(pd.crosstab(data.HEAT, data.AC))

In [226]:
def contingency_coefficent(row, col):
    if row.size != col.size:
        return None
    n = row.size
    c_table = pd.crosstab(row, col)
    exp_table = scipy.stats.contingency.expected_freq(c_table)
    print(pow(c_table - exp_table, 2) / exp_table)
    chi2 = (pow(c_table - exp_table, 2) / exp_table).sum().sum()
    C = pow(chi2 / (chi2 + n), 1/2)
    print(C)
    Ckorr = C * pow(min(c_table.shape) / (min(c_table.shape) - 1), 1/2)
    return Ckorr

In [186]:
x =(((tab - exp)**2)/exp).sum().sum()

In [187]:
pow(x / (x + tab.sum().sum()), 1/2)

0.5907381865270473

In [227]:
contingency_coefficent(data.HEAT, data.AC)

AC                        0             N             Y
HEAT                                                   
Air Exchng       246.835672     13.563523      7.091591
Air-Oil            0.047843     34.262040     13.195850
Elec Base Brd      0.143529     14.186879      5.437528
Electric Rad       0.058884     75.133556     28.958126
Evp Cool           0.020446     10.213016      3.958317
Forced Air        18.251235   4418.773635   1715.168601
Gravity Furnac     0.057248    122.129082     47.094150
Hot Water Rad      0.004714  37557.621300  14506.245577
Ht Pump            0.176831   4582.409556   1769.114199
Ind Unit           0.020446     34.990593     13.490099
No Data         7524.571679      1.068553      2.025671
Wall Furnace       0.457985      5.638147      2.225560
Warm Cool         13.751014   8858.973758   3432.119524
Water Base Brd     0.164384     91.176540     35.102458
0.5907381865270473


0.7235035642841691

In [157]:
(tab / exp) **2

AC                       0         N         Y
HEAT                                          
Air Exchng      125.409862  2.117453  0.497832
Air-Oil           0.000000  2.025390  0.604510
Elec Base Brd     0.000000  1.380947  0.853426
Electric Rad      0.000000  2.368709  0.471903
Evp Cool          0.000000  0.143619  1.331345
Forced Air        0.090621  0.457822  1.209932
Gravity Furnac    0.000000  2.769786  0.316987
Hot Water Rad     0.984373  2.690223  0.347160
Ht Pump           1.142113  0.123416  1.338500
Ind Unit          0.000000  2.585134  0.388309
No Data         237.138648  0.892176  0.907735
Wall Furnace      0.000000  0.865558  1.052495
Warm Cool         0.000000  0.027440  1.376219
Water Base Brd    0.000000  1.902410  0.652011

In [215]:
min(tab.shape)

3